import PrelineScriptWrapper from "./components/PrelineScriptWrapper";
import type { Metadata } from "next";
import { Manrope} from "next/font/google";
import "./globals.css";

const manrope = Manrope({ 
  subsets: ["latin"],
  display: "swap",
  weight:["300","400","500","600","700","800",],  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${manrope.className} antialiased`}
      >  <PrelineScriptWrapper />
        
        {children}
      </body>       
      
    </html>
  );
}
